# Generated by Django 5.2.1 on 2025-05-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_note_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="owner",
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
