# Generated by Django 5.2.1 on 2025-05-23 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_remove_note_user_alter_note_content_alter_note_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
